language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: eckerddevelopers:5F0xCSx0NtjfoJzQSojDKfnK